How To build UnitTest++ for CodeLite:

On Unix like system, simply run the makefile: 
---------------------------------------------
	make 

On Windows with MinGW (no MSYS):
--------------------------------
	Open UnitTest++_Windows.workspace with CodeLite
	Select the proper configuratin (Release/Debug)
	Build

Eran
