#!/bin/bash -e

. $(dirname $(readlink -f $0))/make-weekly-common

# package CodeLite
function build_codelite() {
    cd $ROOT_DIR
    mkdir -p build-release
    cd build-release
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCOPY_WX_LIBS=1 -DWXWIN=$HOME/root -G"MinGW Makefiles"
    mingw32-make -j${cpu_count} install
}

function package_codelite() {
    cd $ROOT_DIR/build-release
    mingw32-make -j${cpu_count} setup

    # cd to the location where our output file exists and upload it
    cd ${ROOT_DIR}/InnoSetup/output
    package_file=$(ls *codelite*.exe)
    echo "Uploading CodeLite installer ${package_file}"
    upload_path="/var/www/html/downloads/codelite/${version}"
    ssh root@codelite.org "mkdir -p ${upload_path}"
    scp "${package_file}" root@codelite.org:${upload_path}
    ssh root@codelite.org \
        "cd ${upload_path} && sha256sum ${package_file} |cut -d' ' -f1 > ${package_file}.sha1 && cat ${package_file}.sha1"
}

# package wxCrafter
function build_wxcrafter() {
    cd $ROOT_DIR
    mkdir -p build-release-wxcapp
    cd build-release-wxcapp
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCOPY_WX_LIBS=1 -DWXWIN=$HOME/root -G"MinGW Makefiles"
    mingw32-make -j${cpu_count} install
}

function package_wxcrafter() {
    cd $ROOT_DIR/build-release-wxcapp
    mingw32-make -j${cpu_count} setup

    # cd to the location where our output file exists and upload it
    cd ${ROOT_DIR}/InnoSetup/output
    package_file=$(ls *wxcrafter*.exe)
    echo "Uploading wxCrafter installer ${package_file}"

    upload_path="/var/www/html/downloads/wxcrafter/${version}"
    ssh root@codelite.org "mkdir -p ${upload_path}"
    scp "${package_file}" root@codelite.org:${upload_path}
    ssh root@codelite.org \
        "cd ${upload_path} && sha256sum ${package_file} |cut -d' ' -f1 > ${package_file}.sha1 && cat ${package_file}.sha1"
}

# clear old installers
rm -fr ${ROOT_DIR}/InnoSetup/output/*.exe

build_codelite
package_codelite

build_wxcrafter
package_wxcrafter
