#!/bin/bash
install_dir=$1
wx_libs=`ls -l ${install_dir}/libwx*.so|awk '{print $9;}'|xargs readlink|xargs readlink`
for lib in ${wx_libs}
do
    echo patchelf --set-rpath '${install_dir}' ${lib}
    patchelf --set-rpath "${install_dir}" ${lib}
done
