@echo off
copy debuggers\*.dll "C:\Program Files\CodeLite\debuggers\"
copy plugins\*.dll "C:\Program Files\CodeLite\plugins\"
copy rc\*.xrc "C:\Program Files\CodeLite\rc\"
copy templates\* "C:\Program Files\CodeLite\templates\"
copy images\* "C:\Program Files\CodeLite\images\"
copy astyle.sample "C:\Program Files\CodeLite\"
copy *.html "C:\Program Files\CodeLite\"
copy config\*.default "C:\Program Files\CodeLite\config\"
copy lexers\Default\*.xml "C:\Program Files\CodeLite\lexers\Default\"
copy lexers\BlackTheme\*.xml "C:\Program Files\CodeLite\lexers\BlackTheme\"
copy CodeLite.exe "C:\Program Files\CodeLite\"
copy bin\*.exe "C:\Program Files\CodeLite\bin\"
