#include "ai/ACPEvent.hpp"

clACPEvent::clACPEvent(wxEventType type, int winid)
    : wxEvent(winid, type)
{
}

wxDEFINE_EVENT(wxEVT_ACP_OUTPUT, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_PROMPT_DONE, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_TOOL_CALL, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_TOOL_CALL_UPDATE, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_USAGE, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_PLAN, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_PERMISSION, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_SESSION_LIST, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_INITIALIZED, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_SESSION_READY, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_ERROR, clACPEvent);
wxDEFINE_EVENT(wxEVT_ACP_TERMINATED, clACPEvent);
