#pragma once

#include "cl_command_event.h"
#include "codelite_exports.h"

#include <wx/event.h>

wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_THINK_SATRTED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_THINK_ENDED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_OUTPUT, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_OUTPUT_DONE, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_CHAT_STARTED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_MODELS_LOADED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_CONFIG_UPDATED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_STARTED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_STOPPED, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_USER_REPLY_TIMEOUT, clLLMEvent);
wxDECLARE_EXPORTED_EVENT(WXDLLIMPEXP_SDK, wxEVT_LLM_USER_REPLY_ERROR, clLLMEvent);
