#include "ai/LLMEvents.hpp"

// LLM events.
wxDEFINE_EVENT(wxEVT_LLM_THINK_SATRTED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_THINK_ENDED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_OUTPUT, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_OUTPUT_DONE, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_CHAT_STARTED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_MODELS_LOADED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_CONFIG_UPDATED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_STARTED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_STOPPED, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_USER_REPLY_TIMEOUT, clLLMEvent);
wxDEFINE_EVENT(wxEVT_LLM_USER_REPLY_ERROR, clLLMEvent);
