//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2014 The CodeLite Team
// file name            : scope_optimizer.cpp
//
// -------------------------------------------------------------------------
// A
//              _____           _      _     _ _
//             /  __ \         | |    | |   (_) |
//             | /  \/ ___   __| | ___| |    _| |_ ___
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/
//              \____/\___/ \__,_|\___\_____/_|\__\___|
//
//                                                  F i l e
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

#define yy_create_buffer scope_optimizer__create_buffer
#define yy_delete_buffer scope_optimizer__delete_buffer
#define yy_scan_buffer scope_optimizer__scan_buffer
#define yy_scan_string scope_optimizer__scan_string
#define yy_scan_bytes scope_optimizer__scan_bytes
#define yy_flex_debug scope_optimizer__flex_debug
#define yy_init_buffer scope_optimizer__init_buffer
#define yy_flush_buffer scope_optimizer__flush_buffer
#define yy_load_buffer_state scope_optimizer__load_buffer_state
#define yy_switch_to_buffer scope_optimizer__switch_to_buffer
#define yyin scope_optimizer_in
#define yyleng scope_optimizer_leng
#define yylex scope_optimizer_lex
#define yyout scope_optimizer_out
#define yyrestart scope_optimizer_restart
#define yytext scope_optimizer_text
#define yylineno scope_optimizer_lineno
#define yywrap scope_optimizer_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
static yyconst short int yy_acclist[435] =
    {   0,
       82,   76,   81,    3,   76,   81,    5,   81,    4,   76,
       81,   76,   81,   14,   76,   81,   76,   81,   26,   76,
       81,   27,   76,   81,   76,   81,   75,   76,   81,   75,
       76,   81,   75,   76,   81,   75,   76,   81,   75,   76,
       81,   75,   76,   81,   75,   76,   81,   75,   76,   81,
       75,   76,   81,   75,   76,   81,   75,   76,   81,   75,
       76,   81,   75,   76,   81,   75,   76,   81,   75,   76,
       81,   75,   76,   81,   75,   76,   81,   75,   76,   81,
       75,   76,   81,   75,   76,   81,   28,   76,   81,   29,
       76,   81,   17,   81,   16,   81,   15,   17,   81,   17,

       81,   21,   81,    6,   21,   81,    8,   81,    7,   21,
       81,   19,   21,   81,   20,   21,   81,   21,   81,   25,
       81,    9,   25,   81,   11,   81,   10,   25,   81,   23,
       25,   81,   24,   25,   81,   25,   81,   80,   81,   81,
       80,   81,   80,   81,   78,   81,   77,   81,   78,   81,
        3,    5,    4,   13,    2,    1,   75,   75,   75,   75,
       75,   75,   75,   37,   75,   75,   75,   75,   75,   75,
       75,   75,   43,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,    6,    8,    7,    9,   11,   10,   79,   12,

       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   67,   75,   75,   75,   75,
       75,   75,   75,   30,   75,   75,   32,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   38,   75,   39,   75,
       75,   75,   22,   75,   42,   75,   75,   75,   75,   75,
       47,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   31,   75,   18,   75,   55,   75,   75,   75,

       75,   75,   75,   75,   40,   75,   41,   75,   75,   44,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   74,   75,   75,
       52,   75,   53,   75,   73,   75,   75,   54,   75,   75,
       75,   75,   35,   75,   58,   75,   75,   59,   75,   45,
       75,   75,   60,   75,   75,   75,   48,   75,   75,   75,
       64,   75,   75,   49,   75,   50,   75,   75,   56,   75,
       51,   75,   75,   75,   75,   75,   75,   34,   75,   36,
       75,   75,   46,   75,   75,   75,   63,   75,   75,   75,
       75,   75,   75,   65,   75,   75,   33,   75,   75,   75,

       61,   75,   75,   75,   75,   66,   75,   68,   75,   75,
       75,   57,   75,   62,   75,   75,   75,   71,   75,   75,
       75,   75,   75,   75,   70,   75,   69,   75,   75,   75,
       75,   75,   72,   75
    } ;

static yyconst short int yy_accept[333] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       19,   22,   25,   27,   30,   33,   36,   39,   42,   45,
       48,   51,   54,   57,   60,   63,   66,   69,   72,   75,
       78,   81,   84,   87,   90,   93,   95,   97,  100,  102,
      104,  107,  109,  112,  115,  118,  120,  122,  125,  127,
      130,  133,  136,  138,  140,  141,  143,  145,  147,  149,
      151,  152,  153,  153,  154,  154,  155,  155,  155,  155,
      156,  157,  158,  158,  158,  159,  160,  161,  162,  163,
      164,  166,  167,  168,  169,  170,  171,  172,  173,  175,

      176,  177,  178,  179,  180,  181,  182,  183,  184,  185,
      186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
      195,  196,  197,  198,  198,  199,  200,  200,  200,  201,
      201,  201,  202,  203,  204,  205,  206,  207,  208,  209,
      210,  211,  212,  213,  214,  215,  216,  217,  218,  219,
      220,  221,  222,  223,  224,  225,  226,  227,  228,  229,
      230,  231,  232,  233,  234,  235,  236,  238,  239,  240,
      241,  242,  243,  244,  244,  244,  244,  244,  246,  247,
      249,  250,  251,  252,  253,  254,  255,  256,  257,  259,
      261,  262,  263,  263,  264,  265,  267,  268,  269,  270,

      271,  273,  274,  275,  276,  277,  278,  279,  280,  281,
      282,  283,  284,  285,  286,  287,  288,  289,  290,  291,
      292,  293,  293,  293,  293,  293,  295,  297,  299,  300,
      301,  302,  303,  304,  305,  307,  309,  310,  312,  313,
      314,  315,  316,  317,  318,  319,  320,  321,  322,  323,
      324,  325,  326,  327,  328,  330,  331,  333,  335,  337,
      338,  340,  341,  342,  343,  345,  347,  348,  350,  352,
      353,  355,  356,  357,  359,  360,  361,  363,  364,  366,
      368,  369,  371,  373,  374,  375,  376,  377,  378,  380,
      382,  383,  385,  386,  387,  389,  390,  391,  392,  393,

      394,  396,  397,  399,  400,  401,  403,  404,  405,  406,
      408,  410,  411,  412,  414,  416,  417,  418,  420,  421,
      422,  423,  424,  425,  427,  429,  430,  431,  432,  433,
      435,  435
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    1,    8,    9,    1,    1,    1,   10,   11,
       12,   13,    1,    1,    1,    1,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   16,   16,    1,    1,    1,
        1,    1,   17,    1,   18,   18,   18,   18,   18,   18,
       19,   19,   19,   19,   19,   20,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
        1,   21,    1,    1,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   19,   32,   33,   34,   35,
       36,   37,   19,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    4,
        1,    1,    1,    1,    5,    6,    3,    6,    7,    7,
        3,    7,    5,    5,    6,    6,    6,    5,    7,    7,
        7,    7,    7,    7,    8,    7,    7,    8,    7,    8,
        7,    8,    7,    8,    7,    7,    1,    1
    } ;

static yyconst short int yy_base[344] =
    {   0,
        0,    0,   46,   47,   60,   73,   86,   99,   55,  104,
       56,   80,  553,  554,  117,  554,  123,   65,  554,  531,
      554,  554,   38,    0,   47,  510,  512,   76,  104,   99,
       78,  513,   80,  517,  524,  509,   95,  518,  104,  112,
      106,  513,  513,  554,  554,  554,  554,  554,   68,  554,
      149,  554,  156,  554,  554,   82,  554,  162,  554,  168,
      554,  554,  163,  554,  554,  528,  165,  554,  554,  167,
      180,  554,  186,  192,  192,  554,  186,  193,  187,  554,
      554,    0,  196,  520,  500,  512,  166,  515,  502,  110,
        0,  501,  176,  509,  496,  495,  501,  491,  183,  183,

      495,  495,  501,  188,  503,  181,  480,  187,  494,  490,
      485,  477,  484,  196,  489,  481,  487,  230,  554,  236,
      242,  248,  554,  254,  260,  554,  260,    0,  554,  259,
        0,  481,  493,  488,  489,  474,  189,  247,  485,  488,
      482,  482,  477,  471,  265,  479,  469,  477,  477,  469,
      470,  473,  472,  460,  468,  454,  455,  461,  458,  451,
      464,  450,  448,  448,  450,  450,    0,  458,  457,  447,
      447,  441,  447,  269,  283,  272,  302,    0,  447,    0,
      448,  438,  436,  444,  433,  438,  432,  437,    0,    0,
      442,  431,  272,  554,  433,    0,  439,  439,  424,  429,

        0,  424,  439,  427,  437,  432,  427,  417,  418,  419,
      423,  428,  427,  418,  407,  414,  420,  412,  417,  404,
      417,  265,    0,  275,    0,    0,    0,    0,  421,  407,
      408,  413,  412,  407,    0,    0,  411,    0,  408,  409,
      407,  396,  392,  408,  390,  404,  403,  400,  391,  397,
      399,  383,  392,  398,    0,  397,    0,    0,    0,  396,
        0,  393,  376,  376,  389,    0,  389,    0,    0,  386,
        0,  389,  375,    0,  383,  369,    0,  370,    0,    0,
      385,    0,    0,  361,  366,  362,  371,  355,    0,    0,
      358,    0,  347,  286,    0,  295,  284,  294,  289,  288,

        0,  275,    0,  288,  278,    0,  277,  264,  277,    0,
        0,  257,  272,    0,    0,  267,  253,    0,  250,  248,
      231,  186,  201,    0,    0,  195,  125,  107,   16,    0,
      554,  330,  338,  346,  354,  362,  370,  378,  382,  388,
      394,  398,  400
    } ;

static yyconst short int yy_def[344] =
    {   0,
      331,    1,  332,  332,  333,  333,  334,  334,  335,  335,
      336,  336,  331,  331,  331,  331,  331,  337,  331,  338,
      331,  331,  331,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  337,  331,  340,  338,  341,  331,
      331,  339,  337,  338,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,

      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  337,  342,  331,  338,
      343,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  337,  337,  338,  338,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  331,  331,  339,  339,  339,  339,  339,  339,

      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  337,  175,  338,  177,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,

      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
        0,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331
    } ;

static yyconst short int yy_nxt[603] =
    {   0,
       14,   15,   16,   17,   17,   17,   15,   18,   19,   20,
       21,   22,   14,   23,   14,   14,   14,   24,   24,   25,
       14,   24,   26,   27,   28,   29,   30,   31,   32,   24,
       33,   24,   34,   24,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   24,   24,   24,   44,   45,   47,   47,
       80,   81,   48,   48,   83,  330,   84,   65,   69,   49,
       49,   51,   52,   53,   53,   53,   51,   66,   67,   70,
       54,   55,   76,   56,   51,   52,   53,   53,   53,   51,
       80,   81,   69,   54,   55,   77,   56,   58,   59,   60,
       60,   60,   58,   70,   80,   81,   61,   62,   87,   63,

       58,   59,   60,   60,   60,   58,   65,   99,   88,   61,
       62,   89,   63,   96,  100,   97,   66,   67,   71,   72,
       73,   73,   73,   71,   73,   72,   74,   74,   74,   73,
       90,   93,  104,   94,  107,  105,   95,  138,  110,   91,
      114,  111,  139,  108,  115,  329,  109,  328,   92,  112,
      118,  119,  120,  120,  120,  118,  113,  120,  119,  121,
      121,  121,  120,  122,  123,  124,  124,  124,  122,  124,
      123,  125,  125,  125,  124,   80,   81,   80,   81,   80,
       81,   71,   72,   73,   73,   73,   71,   73,   72,   73,
       73,   73,   73,   73,   72,   74,   74,   74,   73,   76,

      127,  130,  129,   76,  134,  135,  141,  150,  148,  162,
      155,  159,   77,   79,  142,  151,   77,  149,  156,  327,
      160,  169,  326,  157,  163,  325,  170,  183,  184,  128,
      131,  118,  119,  120,  120,  120,  118,  120,  119,  120,
      120,  120,  120,  120,  119,  121,  121,  121,  120,  122,
      123,  124,  124,  124,  122,  124,  123,  124,  124,  124,
      124,  124,  123,  125,  125,  125,  124,   76,  129,  185,
      324,  193,   76,  176,  174,  194,   76,  186,  193,   79,
       77,  129,  194,  222,  129,   77,  224,  323,  322,   77,
       76,  321,   79,  320,  319,   79,  318,  223,  223,  317,

      223,  316,  315,   77,  314,  223,  223,  223,  223,  223,
      223,  129,  313,  312,  311,  310,  225,  225,  309,  225,
      308,  307,   79,  306,  225,  225,  225,  225,  225,  225,
       46,   46,   46,   46,   46,   46,   46,   46,   50,   50,
       50,   50,   50,   50,   50,   50,   57,   57,   57,   57,
       57,   57,   57,   57,   64,   64,   64,   64,   64,   64,
       64,   64,   68,   68,   68,   68,   68,   68,   68,   68,
       75,  305,   75,   75,   75,   75,   75,   75,   78,  304,
       78,  303,   78,   78,   78,   78,   82,   82,   82,   82,
       75,   75,   75,  302,  301,   75,   78,   78,   78,  300,

      299,   78,  175,  175,  177,  177,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,

      200,  199,  198,  197,  196,  195,  192,  191,  190,  189,
      188,  187,  182,  181,  180,  179,  178,  173,  172,  171,
      168,  167,  166,  165,  164,  161,  158,  154,  153,  152,
      147,  146,  145,  144,  143,  140,  137,  136,  133,  132,
       79,  126,  117,  116,  106,  103,  102,  101,   98,   86,
       85,   79,  331,   13,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331
    } ;

static yyconst short int yy_chk[603] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
       23,   23,    3,    4,   25,  329,   25,    9,   11,    3,
        4,    5,    5,    5,    5,    5,    5,    9,    9,   11,
        5,    5,   18,    5,    6,    6,    6,    6,    6,    6,
       49,   49,   12,    6,    6,   18,    6,    7,    7,    7,
        7,    7,    7,   12,   56,   56,    7,    7,   28,    7,

        8,    8,    8,    8,    8,    8,   10,   33,   28,    8,
        8,   28,    8,   31,   33,   31,   10,   10,   15,   15,
       15,   15,   15,   15,   17,   17,   17,   17,   17,   17,
       29,   30,   37,   30,   39,   37,   30,   90,   40,   29,
       41,   40,   90,   39,   41,  328,   39,  327,   29,   40,
       51,   51,   51,   51,   51,   51,   40,   53,   53,   53,
       53,   53,   53,   58,   58,   58,   58,   58,   58,   60,
       60,   60,   60,   60,   60,   63,   63,   67,   67,   70,
       70,   71,   71,   71,   71,   71,   71,   73,   73,   73,
       73,   73,   73,   74,   74,   74,   74,   74,   74,   75,

       77,   79,   78,   83,   87,   87,   93,  100,   99,  108,
      104,  106,   75,   78,   93,  100,   83,   99,  104,  326,
      106,  114,  323,  104,  108,  322,  114,  137,  137,   77,
       79,  118,  118,  118,  118,  118,  118,  120,  120,  120,
      120,  120,  120,  121,  121,  121,  121,  121,  121,  122,
      122,  122,  122,  122,  122,  124,  124,  124,  124,  124,
      124,  125,  125,  125,  125,  125,  125,  127,  130,  138,
      321,  145,  222,  130,  127,  145,  174,  138,  193,  130,
      127,  176,  193,  174,  224,  222,  176,  320,  319,  174,
      175,  317,  176,  316,  313,  224,  312,  175,  175,  309,

      175,  308,  307,  175,  305,  175,  175,  175,  175,  175,
      175,  177,  304,  302,  300,  299,  177,  177,  298,  177,
      297,  296,  177,  294,  177,  177,  177,  177,  177,  177,
      332,  332,  332,  332,  332,  332,  332,  332,  333,  333,
      333,  333,  333,  333,  333,  333,  334,  334,  334,  334,
      334,  334,  334,  334,  335,  335,  335,  335,  335,  335,
      335,  335,  336,  336,  336,  336,  336,  336,  336,  336,
      337,  293,  337,  337,  337,  337,  337,  337,  338,  291,
      338,  288,  338,  338,  338,  338,  339,  339,  339,  339,
      340,  340,  340,  287,  286,  340,  341,  341,  341,  285,

      284,  341,  342,  342,  343,  343,  281,  278,  276,  275,
      273,  272,  270,  267,  265,  264,  263,  262,  260,  256,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  237,  234,  233,  232,
      231,  230,  229,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  200,  199,  198,  197,  195,  192,  191,
      188,  187,  186,  185,  184,  183,  182,  181,  179,  173,
      172,  171,  170,  169,  168,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,

      151,  150,  149,  148,  147,  146,  144,  143,  142,  141,
      140,  139,  136,  135,  134,  133,  132,  117,  116,  115,
      113,  112,  111,  110,  109,  107,  105,  103,  102,  101,
       98,   97,   96,   95,   94,   92,   89,   88,   86,   85,
       84,   66,   43,   42,   38,   36,   35,   34,   32,   27,
       26,   20,   13,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
#define PRE_PROCESSOR_STATE 1

#define CATCH_STATE 2

#define FOR_STATE 3

#define C_COMMENT_STATE 4

#define CPP_COMMENT_STATE 5

// Avoid spam output
#ifdef  ECHO
#undef  ECHO
#endif
#define ECHO

// Never exit
#ifdef  YY_FATAL_ERROR
#undef  YY_FATAL_ERROR
#endif
#define YY_FATAL_ERROR(msg)

#include <vector>
#include <string>

struct ScopeEntry {
	std::string str;
	int         line;

	ScopeEntry() : line(-1) {}
	void clear() {
		line = -1;
		str.clear();
	}
};

static std::vector<ScopeEntry> scope_stack;
static ScopeEntry              current_scope;
static int                     current_state       = INITIAL;
static int                     current_brace_depth = 1;
static std::string             catch_for_scope;

#define PUSH_SCOPE(scope) {\
	if(scope.line == -1)\
		scope.line = scope_optimizer_lineno;\
	scope_stack.push_back(scope);\
}


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 332 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 554 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
{
	BEGIN(CPP_COMMENT_STATE);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
	BEGIN(C_COMMENT_STATE);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
{current_scope.str += " ";}
	YY_BREAK
case 4:
YY_RULE_SETUP
{current_scope.str += " ";}
	YY_BREAK
case 5:
YY_RULE_SETUP
{current_scope.str += " ";}
	YY_BREAK
case 6:
YY_RULE_SETUP
{catch_for_scope += " ";}
	YY_BREAK
case 7:
YY_RULE_SETUP
{catch_for_scope += " ";}
	YY_BREAK
case 8:
YY_RULE_SETUP
{catch_for_scope += " ";}
	YY_BREAK
case 9:
YY_RULE_SETUP
{catch_for_scope += " ";}
	YY_BREAK
case 10:
YY_RULE_SETUP
{catch_for_scope += " ";}
	YY_BREAK
case 11:
YY_RULE_SETUP
{catch_for_scope += " ";}
	YY_BREAK
case 12:
YY_RULE_SETUP
{/* eat a string */}
	YY_BREAK
case 13:
YY_RULE_SETUP
{/* eat a string */}
	YY_BREAK
case 14:
YY_RULE_SETUP
{BEGIN(PRE_PROCESSOR_STATE);}
	YY_BREAK
case 15:
YY_RULE_SETUP
{} /* continue same state on next line */
	YY_BREAK
case 16:
YY_RULE_SETUP
{BEGIN(current_state);}
	YY_BREAK
case 17:
YY_RULE_SETUP
{} /* consume it */
	YY_BREAK
case 18:
YY_RULE_SETUP
{
	current_state = CATCH_STATE;
	catch_for_scope.clear();
	BEGIN(CATCH_STATE);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
{catch_for_scope += ";";}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
	catch_for_scope += ";"; 
	current_state = INITIAL; 
	BEGIN(INITIAL);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
	// default keep the current token
	catch_for_scope += yytext;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
	current_state = FOR_STATE;
	BEGIN(FOR_STATE);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
	current_brace_depth++;
	catch_for_scope += yytext;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
	current_brace_depth--;
	if(current_brace_depth == 0) {
		current_state = INITIAL; 
		catch_for_scope += ";";
		current_brace_depth = 1;
		BEGIN(INITIAL);
	} else {
		catch_for_scope += yytext;
	}
}
	YY_BREAK
case 25:
YY_RULE_SETUP
{
	// default keep the current token
	catch_for_scope += yytext;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
{
	current_scope.str += "(";
	if(current_scope.str.empty() == false) {
		PUSH_SCOPE(current_scope);
	}
	current_scope.clear();
}
	YY_BREAK
case 27:
YY_RULE_SETUP
{
	if ( !scope_stack.empty() ) {
		current_scope = scope_stack.back();
		scope_stack.pop_back();
		
		current_scope.str += ")";
	} else {
		current_scope.clear();
	}
}
	YY_BREAK
case 28:
YY_RULE_SETUP
{
	current_scope.str += "{";
	PUSH_SCOPE(current_scope);
	current_scope.clear();
	
	if(catch_for_scope.empty() == false)
		current_scope.str += catch_for_scope;
	catch_for_scope.clear();
}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
	if ( !scope_stack.empty() ) {
		current_scope = scope_stack.back();
		
		scope_stack.pop_back();
		current_scope.str += "}";
	} else {
		current_scope.clear();
	}
}
	YY_BREAK
case 30:
YY_RULE_SETUP
{current_scope.str += yytext;}
	YY_BREAK
case 31:
YY_RULE_SETUP
{}
	YY_BREAK
case 32:
YY_RULE_SETUP
{}
	YY_BREAK
case 33:
YY_RULE_SETUP
{}
	YY_BREAK
case 34:
YY_RULE_SETUP
{}
	YY_BREAK
case 35:
YY_RULE_SETUP
{}
	YY_BREAK
case 36:
YY_RULE_SETUP
{}
	YY_BREAK
case 37:
YY_RULE_SETUP
{}
	YY_BREAK
case 38:
YY_RULE_SETUP
{}
	YY_BREAK
case 39:
YY_RULE_SETUP
{}
	YY_BREAK
case 40:
YY_RULE_SETUP
{}
	YY_BREAK
case 41:
YY_RULE_SETUP
{}
	YY_BREAK
case 42:
YY_RULE_SETUP
{}
	YY_BREAK
case 43:
YY_RULE_SETUP
{}
	YY_BREAK
case 44:
YY_RULE_SETUP
{}
	YY_BREAK
case 45:
YY_RULE_SETUP
{}
	YY_BREAK
case 46:
YY_RULE_SETUP
{}
	YY_BREAK
case 47:
YY_RULE_SETUP
{}
	YY_BREAK
case 48:
YY_RULE_SETUP
{}
	YY_BREAK
case 49:
YY_RULE_SETUP
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
{}
	YY_BREAK
case 52:
YY_RULE_SETUP
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
{}
	YY_BREAK
case 54:
YY_RULE_SETUP
{}
	YY_BREAK
case 55:
YY_RULE_SETUP
{ current_scope.str += yytext; }
	YY_BREAK
case 56:
YY_RULE_SETUP
{ current_scope.str += yytext; }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ current_scope.str += yytext; }
	YY_BREAK
case 58:
YY_RULE_SETUP
{}
	YY_BREAK
case 59:
YY_RULE_SETUP
{}
	YY_BREAK
case 60:
YY_RULE_SETUP
{}
	YY_BREAK
case 61:
YY_RULE_SETUP
{}
	YY_BREAK
case 62:
YY_RULE_SETUP
{}
	YY_BREAK
case 63:
YY_RULE_SETUP
{}
	YY_BREAK
case 64:
YY_RULE_SETUP
{}
	YY_BREAK
case 65:
YY_RULE_SETUP
{}
	YY_BREAK
case 66:
YY_RULE_SETUP
{}
	YY_BREAK
case 67:
YY_RULE_SETUP
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
{}
	YY_BREAK
case 69:
YY_RULE_SETUP
{}
	YY_BREAK
case 70:
YY_RULE_SETUP
{}
	YY_BREAK
case 71:
YY_RULE_SETUP
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
{}
	YY_BREAK
case 73:
YY_RULE_SETUP
{ current_scope.str += yytext; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ current_scope.str += yytext; }
	YY_BREAK
case 75:
case 76:
YY_RULE_SETUP
{
	if(catch_for_scope.empty() == false)
		catch_for_scope.clear();
		
	// default keep the current token
	current_scope.str += yytext;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
{
	BEGIN(current_state);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
{}
	YY_BREAK
case 79:
YY_RULE_SETUP
{
	BEGIN(current_state);
}
	YY_BREAK
case 80:
YY_RULE_SETUP
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PRE_PROCESSOR_STATE):
case YY_STATE_EOF(CATCH_STATE):
case YY_STATE_EOF(FOR_STATE):
case YY_STATE_EOF(C_COMMENT_STATE):
case YY_STATE_EOF(CPP_COMMENT_STATE):
{
	if(current_scope.str.empty() == false) {
		PUSH_SCOPE(current_scope);
		current_scope.clear();
	}
	yyterminate();
}
	YY_BREAK
case 81:
YY_RULE_SETUP
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 332 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 332 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 331);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


int yywrap() {
	return 1; 
}

void scope_optimizer_clean()
{
	yy_flush_buffer(YY_CURRENT_BUFFER);
	yy_delete_buffer(YY_CURRENT_BUFFER);
	
	scope_stack.clear();
	current_scope.clear();
	current_state = INITIAL;
	current_brace_depth = 1;
	catch_for_scope.clear();
}

int OptimizeScope(const std::string &inputScope, std::string &optimizedScope, int localsLine, std::string &localsScope)
{
	BEGIN INITIAL;
	yy_scan_string(inputScope.c_str());
	
	int rc = scope_optimizer_lex();
	if (scope_stack.empty()) {
		optimizedScope = inputScope;
		scope_optimizer_clean();
		return rc;
	}
	
	std::string tmp_scope;
	for (size_t i = 0; i < scope_stack.size(); i++) {
		tmp_scope += scope_stack.at(i).str;
		if(scope_stack.at(i).line >= localsLine) {
			localsScope += scope_stack.at(i).str;
		}
	}

	// if the current scope is not empty, terminate it with ';' and return
	if ( tmp_scope.empty() == false ) {
		tmp_scope  += ";";
		optimizedScope = tmp_scope;
	}
	scope_optimizer_clean();
	return rc;
}

