//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2009 by Eran Ifrah
// file name            : svn_copy_dialog.h
//
// -------------------------------------------------------------------------
// A
//              _____           _      _     _ _
//             /  __ \         | |    | |   (_) |
//             | /  \/ ___   __| | ___| |    _| |_ ___
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/
//              \____/\___/ \__,_|\___\_____/_|\__\___|
//
//                                                  F i l e
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

#ifndef __svn_copy_dialog__
#define __svn_copy_dialog__

/**
@file
Subclass of SvnCopyDialogBase, which is generated by wxFormBuilder.
*/

#include "subversion2_ui.h"

/** Implementing SvnCopyDialogBase */
class SvnCopyDialog : public SvnCopyDialogBase
{
public:
	/** Constructor */
	SvnCopyDialog( wxWindow* parent );

	void     SetSourceURL(const wxString &url);
	void     SetTargetURL(const wxString &url);
	wxString GetMessage();
	wxString GetSourceURL();
	wxString GetTargetURL();
};

#endif // __svn_copy_dialog__
