#include "clDockerEvents.h"

wxDEFINE_EVENT(wxEVT_DOCKER_KILL_CONTAINER, clCommandEvent);
wxDEFINE_EVENT(wxEVT_DOCKER_LIST_CONTAINERS, clCommandEvent);
wxDEFINE_EVENT(wxEVT_DOCKER_LIST_IMAGES, clCommandEvent);
wxDEFINE_EVENT(wxEVT_DOCKER_CLEAR_UNUSED_IMAGES, clCommandEvent);
wxDEFINE_EVENT(wxEVT_DOCKER_ATTACH_TERMINAL, clCommandEvent);
