.TH CODELITE_FIX_FILES 1 2014-04-11
.SH NAME
codelite_fix_files \- convert a CodeLite project and workspace from the DOS
environment to the *nix environment
.SH SYNOPSIS
.B codelite_fix_files
.SH DESCRIPTION
.B codelite_fix_files
is a trivial script which converts all CodeLite project files (*.project) and
workspace files (*.workspace) in the current directory and all its
subdirectories from the DOS environment to the *nix environment.
.SH SEE ALSO
.BR codelite (1),
.BR codelite-make (1)
.PP
CodeLite online documentation
\(lahttp://codelite.org/LiteEditor/Documentation\(ra
