#ifndef __renamefiledlg__
#define __renamefiledlg__

/**
@file
Subclass of RenameFileBaseDlg, which is generated by wxFormBuilder.
*/

#include "renamefilebasedlg.h"
#include "include_finder.h"
#include <map>

struct IncludeStatementEntry {
	IncludeStatement statement;
	bool             checked;
};

/** Implementing RenameFileBaseDlg */
class RenameFileDlg : public RenameFileBaseDlg
{
	enum {
		RFD_Select,
		RFD_UnSelect,
		RFD_None
	};

	std::map<int, IncludeStatementEntry> m_entries;
protected:
	// Handlers for RenameFileBaseDlg events.
	void OnFileSelected( wxCommandEvent& event );
	void OnFileToggeled( wxCommandEvent& event );

	void DoSelectItem( int idx, int check );
public:
	/** Constructor */
	RenameFileDlg( wxWindow* parent, const wxString &replaceWith, std::vector<IncludeStatement> &matches );
	virtual ~RenameFileDlg();
	std::vector<IncludeStatement> GetMatches()     const;
	wxString                      GetReplaceWith() const;
};

#endif // __renamefiledlg__
