#ifndef __threebuttondlg__
#define __threebuttondlg__

/**
@file
Subclass of ThreeButtonBaseDlg, which is generated by wxFormBuilder.
*/

#include "threebuttonbasedlg.h"

/** Implementing ThreeButtonBaseDlg */
class ThreeButtonDlg : public ThreeButtonBaseDlg
{
	
protected:
	void OnButtonYes(wxCommandEvent &e);
	void OnButtonNo(wxCommandEvent &e);
	void OnButtonCancel(wxCommandEvent &e);
	
public:
	/** Constructor */
	ThreeButtonDlg( wxWindow* parent, const wxString &msg, const wxString &caption );
	bool GetDontAskMeAgain() const {return m_checkBoxRememberMyAnwer->GetValue();}
};

#endif // __threebuttondlg__
