#ifndef WXCUSTOMCONTROLS_HPP
#define WXCUSTOMCONTROLS_HPP

#ifdef __WXGTK__

// GTK2 & 3
#define wxUSE_NATIVE_CHOICE 0
#define wxUSE_NATIVE_BUTTON 0
#define wxUSE_NATIVE_SCROLLBAR 0
#define wxUSE_NATIVE_MENUBAR 1
#define wxUSE_NATIVE_CAPTION 1
#elif defined(__WXOSX__)
// macOS
#define wxUSE_NATIVE_CHOICE 1
#define wxUSE_NATIVE_BUTTON 0
#define wxUSE_NATIVE_SCROLLBAR 1
#define wxUSE_NATIVE_MENUBAR 1
#define wxUSE_NATIVE_CAPTION 1
#else
// Windows
#define wxUSE_NATIVE_CHOICE 0
#define wxUSE_NATIVE_BUTTON 0
#define wxUSE_NATIVE_SCROLLBAR 0
#define wxUSE_NATIVE_MENUBAR 0
#define wxUSE_NATIVE_CAPTION 1
#endif
#endif // WXCUSTOMCONTROLS_HPP
