#ifndef __svnlogdlg__
#define __svnlogdlg__

/**
@file
Subclass of SvnLogBaseDialog, which is generated by wxFormBuilder.
*/

#include "svnlogbasedlg.h"

/** Implementing SvnLogBaseDialog */
class SvnLogDlg : public SvnLogBaseDialog
{
public:
	wxString GetFilePath() const{return m_filePicker->GetPath();}
	wxString GetFromRevision() const{return m_textCtrlFromRevision->GetValue();}
	wxString GetToRevision() const {return m_textCtrlToRevision->GetValue();}
	
public:
	/** Constructor */
	SvnLogDlg( wxWindow* parent );
};

#endif // __svnlogdlg__

