//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2008 by Eran Ifrah
// file name            : batchbuilddlg.h
//
// -------------------------------------------------------------------------
// A
//              _____           _      _     _ _
//             /  __ \         | |    | |   (_) |
//             | /  \/ ___   __| | ___| |    _| |_ ___
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/
//              \____/\___/ \__,_|\___\_____/_|\__\___|
//
//                                                  F i l e
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

#ifndef __batchbuilddlg__
#define __batchbuilddlg__

/**
@file
Subclass of BatchBuildBaseDlg, which is generated by wxFormBuilder.
*/

#include "BatchBuildBaseDlg.hpp"
#include "shell_command.h"

#include <list>

/** Implementing BatchBuildBaseDlg */
class BatchBuildDlg : public BatchBuildBaseDlg
{
    void DoInitialize();
    void DoSaveBatchBuildOrder();

public:
    int m_cmd;

protected:
    // Handlers for BatchBuildBaseDlg events.
    void OnItemSelected(wxCommandEvent& event);
    void OnItemToggled(wxCommandEvent& event) override;
    void OnBuild(wxCommandEvent& event) override;
    void OnBuildUI(wxUpdateUIEvent& event) override;
    void OnClean(wxCommandEvent& event) override;
    void OnCleanUI(wxUpdateUIEvent& event) override;
    void OnCheckAll(wxCommandEvent& event) override;
    void OnUnCheckAll(wxCommandEvent& event) override;
    void OnMoveUp(wxCommandEvent& event) override;
    void OnMoveUpUI(wxUpdateUIEvent& event) override;
    void OnMoveDown(wxCommandEvent& event) override;
    void OnMoveDownUI(wxUpdateUIEvent& event) override;
    void OnClose(wxCommandEvent& event) override;

public:
    /** Constructor */
    BatchBuildDlg(wxWindow* parent);
    std::list<QueueCommand> GetBuildInfoList() const;
};

#endif // __batchbuilddlg__
