//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: BuildTabSettings.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CODELITE_LITEEDITOR_BUILDTABSETTINGS_BASE_CLASSES_H
#define _CODELITE_LITEEDITOR_BUILDTABSETTINGS_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/checkbox.h>
#include <wx/stattext.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class BuildTabSettingsBase : public wxPanel
{
protected:
    wxCheckBox* m_checkBoxSkipWarnings;
    wxCheckBox* m_checkBoxScrollToError;
    wxStaticText* m_staticText37;
    wxChoice* m_choiceMarkerStyle;

protected:
    virtual void OnChange(wxCommandEvent& event) { event.Skip(); }

public:
    wxCheckBox* GetCheckBoxSkipWarnings() { return m_checkBoxSkipWarnings; }
    wxCheckBox* GetCheckBoxScrollToError() { return m_checkBoxScrollToError; }
    wxStaticText* GetStaticText37() { return m_staticText37; }
    wxChoice* GetChoiceMarkerStyle() { return m_choiceMarkerStyle; }
    BuildTabSettingsBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition,
                         const wxSize& size = wxSize(-1, -1), long style = wxTAB_TRAVERSAL);
    virtual ~BuildTabSettingsBase();
};

#endif
