#ifndef __cc_box__
#define __cc_box__

/**
@file
Subclass of CCBoxBase, which is generated by wxFormBuilder.
*/

#include "cc_boxbase.h"
#include "entry.h"
#include <vector>

/** Implementing CCBoxBase */
class CCBox : public CCBoxBase
{
protected:
	// Handlers for CCBoxBase events.
	void OnItemActivated( wxListEvent& event );
	void OnItemDeSelected( wxListEvent& event );
	void OnItemSelected( wxListEvent& event );
	void OnKeyDown( wxListEvent& event );
	
protected:
	// helper methods
	int GetImageId(const TagEntry &entry);
	void Initialize(const std::vector<TagEntryPtr> &tags, const wxString &word, bool showFullDecl);
	
public:
	/** Constructor */
	CCBox( wxWindow* parent );
};

#endif // __cc_box__
