//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2008 by Eran Ifrah                            
// file name            : commentpage.h              
//                                                                          
// -------------------------------------------------------------------------
// A                                                                        
//              _____           _      _     _ _                            
//             /  __ \         | |    | |   (_) |                           
//             | /  \/ ___   __| | ___| |    _| |_ ___                      
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )                     
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/                     
//              \____/\___/ \__,_|\___\_____/_|\__\___|                     
//                                                                          
//                                                  F i l e                 
//                                                                          
//    This program is free software; you can redistribute it and/or modify  
//    it under the terms of the GNU General Public License as published by  
//    the Free Software Foundation; either version 2 of the License, or     
//    (at your option) any later version.                                   
//                                                                          
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
 #ifndef __commentpage__
#define __commentpage__

/**
@file
Subclass of CommentPageBase, which is generated by wxFormBuilder.
*/

#include "commentpagebase.h"

/** Implementing CommentPageBase */
class CommentPage : public CommentPageBase
{
protected:
	// Handlers for CommentPageBase events.
	void Initialize();
	void OnUseAtPrefix(wxCommandEvent &e);
	void DoSetPrefix();
	
public:
	/** Constructor */
	CommentPage( wxWindow* parent );
	
	void Save();
};

#endif // __commentpage__
