#ifndef __dbgcommanddlg__
#define __dbgcommanddlg__

/**
@file
Subclass of DbgCommandBaseDlg, which is generated by wxFormBuilder.
*/

#include "dbgcommandbasedlg.h"

/** Implementing DbgCommandBaseDlg */
class DbgCommandDlg : public DbgCommandBaseDlg
{
public:
	/** Constructor */
	DbgCommandDlg( wxWindow* parent );
	wxString GetCommand(){return m_textCtrlCommand->GetValue();}
	wxString GetName(){return m_textCtrlName->GetValue();}
	void SetName(const wxString &name){m_textCtrlName->SetValue(name);}
	void SetCommand(const wxString &cmd){m_textCtrlCommand->SetValue(cmd);}
	bool IsSubMenu(){return m_checkBox1->GetValue();}
	void SetAsSubMenu(bool b){m_checkBox1->SetValue(b);}
};

#endif // __dbgcommanddlg__
