//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2008 by Eran Ifrah
// file name            : editorsettingsdialogs.h
//
// -------------------------------------------------------------------------
// A
//              _____           _      _     _ _
//             /  __ \         | |    | |   (_) |
//             | /  \/ ___   __| | ___| |    _| |_ ___
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/
//              \____/\___/ \__,_|\___\_____/_|\__\___|
//
//                                                  F i l e
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

#ifndef __editorsettingsdialogs__
#define __editorsettingsdialogs__

/**
@file
Subclass of EditorSettingsDialogsBase, which is generated by wxFormBuilder.
*/

#include "editorsettingsdialogsbase.h"
#include "treebooknodebase.h"

/** Implementing EditorSettingsDialogsBase */
class EditorSettingsDialogs
			: public EditorSettingsDialogsBase
			, public TreeBookNode<EditorSettingsDialogs>
{
	bool bAdjustCPUNumber;
	bool bReplaceWrapAroundAnswer;
	bool bFindNextWrapAroundAnswer;
	bool bBuildBeforeDebug;
	bool bCreateSwappedFile;

	int AdjustCPUNumber_idx;
	int ReplaceWrapAroundAnswer_idx;
	int FindNextWrapAroundAnswer_idx;
	int BuildBeforeDebug_idx;
	int CreateSwappedFile_idx;

public:
	/** Constructor */
	EditorSettingsDialogs( wxWindow* parent );
	virtual ~EditorSettingsDialogs();
	void Save(OptionsConfigPtr options);
};

#endif // __editorsettingsdialogs__
