//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2014 The CodeLite Team
// file name            : editorsettingsdockingwindowsbase.h
//
// -------------------------------------------------------------------------
// A
//              _____           _      _     _ _
//             /  __ \         | |    | |   (_) |
//             | /  \/ ___   __| | ___| |    _| |_ ___
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/
//              \____/\___/ \__,_|\___\_____/_|\__\___|
//
//                                                  F i l e
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: editor_options_docking_windows.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef EDITOR_OPTIONS_DOCKING_WINDOWS_BASE_CLASSES_H
#define EDITOR_OPTIONS_DOCKING_WINDOWS_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/statbox.h>
#include <wx/checkbox.h>
#include <wx/radiobox.h>

class EditorSettingsDockingWindowsBase : public wxPanel
{
protected:
    wxCheckBox* m_checkBoxHideOutputPaneOnClick;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfBuild;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfSearch;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfReplace;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfReferences;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfOutput;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfTrace;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfTasks;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfBuildQ;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfCppCheck;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfSvn;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfCscope;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfGit;
    wxCheckBox* m_checkBoxHideOutputPaneNotIfDebug;
    wxCheckBox* m_checkBoxDontFoldSearchResults;
    wxCheckBox* m_checkBoxFindBarAtBottom;
    wxCheckBox* m_checkBoxShowDebugOnRun;
    wxRadioBox* m_radioBoxHint;
    wxRadioBox* m_radioBoxTabControlStyle;
    wxCheckBox* m_checkBoxHideCaptions;

protected:
    virtual void OnHideOutputPaneNotIfDebugUI(wxUpdateUIEvent& event) { event.Skip(); }

public:
    EditorSettingsDockingWindowsBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxTAB_TRAVERSAL);
    virtual ~EditorSettingsDockingWindowsBase();
};

#endif
