#ifndef __listctrlpanel__
#define __listctrlpanel__

/**
@file
Subclass of ListCtrlPanelBase, which is generated by wxFormBuilder.
*/

#include "listctrlpanelbase.h"
#include "debugger.h"

/** Implementing ListCtrlPanelBase */
class ListCtrlPanel : public ListCtrlPanelBase
{
protected:
	// Handlers for ListCtrlPanelBase events.
	void OnItemActivated( wxListEvent& event );
	void SetColumnText ( long indx, long column, const wxString &rText );
	wxString GetColumnText(long index, long column);

public:
	/** Constructor */
	ListCtrlPanel( wxWindow* parent );
	void Update(const StackEntryArray &stackArr);
	void Clear();
};

#endif // __listctrlpanel__
