//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2008 by Eran Ifrah
// file name            : newkeyshortcutdlg.h
//
// -------------------------------------------------------------------------
// A
//              _____           _      _     _ _
//             /  __ \         | |    | |   (_) |
//             | /  \/ ___   __| | ___| |    _| |_ ___
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/
//              \____/\___/ \__,_|\___\_____/_|\__\___|
//
//                                                  F i l e
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
#ifndef __newkeyshortcutdlg__
#define __newkeyshortcutdlg__

/**
@file
Subclass of NewKeyShortcutBaseDlg, which is generated by wxFormBuilder.
*/

#include "manager.h"
#include "newkeyshortcutbasedlg.h"

/** Implementing NewKeyShortcutBaseDlg */
class NewKeyShortcutDlg : public NewKeyShortcutBaseDlg
{
	MenuItemData m_mid;

protected:
	// Handlers for NewKeyShortcutBaseDlg events.
	void OnKeyDown( wxKeyEvent& event );
	void OnButtonClear(wxCommandEvent &event);

	wxString ToString(wxKeyEvent &e);

public:
	/** Constructor */
	NewKeyShortcutDlg( wxWindow* parent, const MenuItemData &mid );
	wxString GetAccel() {
		return m_textCtrl1->GetValue();
	}
};

#endif // __newkeyshortcutdlg__
