#ifndef __ps_linker_page__
#define __ps_linker_page__

/**
@file
Subclass of PSLinkPageBase, which is generated by wxFormBuilder.
*/

#include "project_settings_base_dlg.h"
#include "project_settings_dlg.h"

//// end generated include
class ProjectSettingsDlg;
class PSGeneralPage;

/** Implementing PSLinkPageBase */
class PSLinkerPage : public PSLinkPageBase, public IProjectSettingsPage
{
	ProjectSettingsDlg *m_dlg;
	PSGeneralPage*      m_gp;

protected:
	// Handlers for PSLinkPageBase events.
	void OnCheckLinkerNeeded( wxCommandEvent& event );
	void OnLinkerNotNeededUI( wxUpdateUIEvent& event );
	void OnCmdEvtVModified( wxCommandEvent& event );
	void OnButtonAddLinkerOptions( wxCommandEvent& event );
	void OnAddLibraryPath( wxCommandEvent& event );
	void OnAddLibrary( wxCommandEvent& event );
	void OnProjectCustumBuildUI(wxUpdateUIEvent& event);

public:
	/** Constructor */
	PSLinkerPage( wxWindow* parent, ProjectSettingsDlg *dlg, PSGeneralPage *gp );
	//// end generated class members

	virtual void Load(BuildConfigPtr buildConf);
	virtual void Save(BuildConfigPtr buildConf, ProjectSettingsPtr projSettingsPtr);
	virtual void Clear();

};

#endif // __ps_linker_page__
