//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef RENAME_SYMBOOL_DLG_BASE_CLASSES_H
#define RENAME_SYMBOOL_DLG_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/splitter.h>
#include <wx/panel.h>
#include <wx/dataview.h>
#include <wx/button.h>
#include <wx/stc/stc.h>
#include <wx/statline.h>
#include <wx/bannerwindow.h>
#include <wx/checklst.h>

class RenameSymbolBase : public wxDialog
{
protected:
    enum {
        ID_CHECK_ALL = 1001,
        ID_UNCHECK_ALL = 1002,
    };
protected:
    wxBoxSizer* bSizer1;
    wxBoxSizer* bSizer4;
    wxStaticText* m_staticText31;
    wxTextCtrl* m_textCtrlNewName;
    wxSplitterWindow* m_splitter7;
    wxPanel* m_splitterPage11;
    wxBoxSizer* bSizer2;
    wxDataViewListCtrl* m_dvListCtrl;
    wxBoxSizer* boxSizer53;
    wxButton* m_buttonCheckAll;
    wxButton* m_buttonUncheckAll;
    wxPanel* m_splitterPage15;
    wxBoxSizer* boxSizer3;
    wxStyledTextCtrl* m_preview;
    wxStaticLine* m_staticLine55;
    wxBoxSizer* bSizer3;
    wxButton* m_buttonOk;
    wxButton* m_buttonCancel;

protected:
    virtual void OnSelection(wxDataViewEvent& event) { event.Skip(); }
    virtual void OnCheckAll(wxCommandEvent& event) { event.Skip(); }
    virtual void OnUncheckAll(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButtonOK(wxCommandEvent& event) { event.Skip(); }

public:
    RenameSymbolBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Rename Symbol"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~RenameSymbolBase();
};


class SelectProjectsDlgBase : public wxDialog
{
protected:
    enum {
        ID_CHECK_ALL = 1001,
        ID_UNCHECK_ALL = 1002,
    };
protected:
    wxBoxSizer* boxSizer25;
    wxBannerWindow* m_banner45;
    wxBoxSizer* boxSizer33;
    wxCheckListBox* m_checkListBoxProjects;
    wxBoxSizer* boxSizer35;
    wxButton* m_button37;
    wxButton* m_button39;
    wxBoxSizer* boxSizer27;
    wxButton* m_button29;
    wxButton* m_button31;

protected:
    virtual void OnSelectAll(wxCommandEvent& event) { event.Skip(); }
    virtual void OnUnSelectAll(wxCommandEvent& event) { event.Skip(); }

public:
    SelectProjectsDlgBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Select Projects"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~SelectProjectsDlgBase();
};

#endif
