//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// copyright            : (C) 2008 by Eran Ifrah                            
// file name            : taskpanel.h              
//                                                                          
// -------------------------------------------------------------------------
// A                                                                        
//              _____           _      _     _ _                            
//             /  __ \         | |    | |   (_) |                           
//             | /  \/ ___   __| | ___| |    _| |_ ___                      
//             | |    / _ \ / _  |/ _ \ |   | | __/ _ )                     
//             | \__/\ (_) | (_| |  __/ |___| | ||  __/                     
//              \____/\___/ \__,_|\___\_____/_|\__\___|                     
//                                                                          
//                                                  F i l e                 
//                                                                          
//    This program is free software; you can redistribute it and/or modify  
//    it under the terms of the GNU General Public License as published by  
//    the Free Software Foundation; either version 2 of the License, or     
//    (at your option) any later version.                                   
//                                                                          
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

#ifndef __taskpanel__
#define __taskpanel__

/**
@file
Subclass of TaskBasePanel, which is generated by wxFormBuilder.
*/

#include "taskbasepanel.h"
#include "search_thread.h"

/** Implementing TaskBasePanel */
class TaskPanel : public TaskBasePanel
{
	SearchResultList m_results;
private:
	void DoDisplayResults();
	void DoClearResults();
	
protected:
	// Handlers for TaskBasePanel events.
	void OnSearch( wxCommandEvent& event );
	void OnItemActivated( wxListEvent& event );
	void OnSearchThread(wxCommandEvent &e);
	void OnStop(wxCommandEvent &e);
	void OnFilter(wxCommandEvent &e);
	void OnClear(wxCommandEvent &e);
	void OnClearUI(wxUpdateUIEvent &e);
	
public:
	/** Constructor */
	TaskPanel( wxWindow* parent );
	
};

#endif // __taskpanel__
