#!/bin/sh
echo "Running postinst step..."
\rm -f ${HOME}/.codelite/config/liteeditor.xml
echo "Creating desktop shortcut for CodeLite..."
cp /usr/share/applications/codelite.desktop ~/Desktop/
echo "Done"

