.PHONY: clean All

All:
	@echo "----------Building project:[ codelite_terminal - Release ]----------"
	@$(MAKE) -f  "codelite_terminal.mk"
clean:
	@echo "----------Cleaning project:[ codelite_terminal - Release ]----------"
	@$(MAKE) -f  "codelite_terminal.mk" clean
