#include "ChatAIEvents.hpp"

wxDEFINE_EVENT(wxEVT_OLLAMA_THINKING, LLMEvent);
wxDEFINE_EVENT(wxEVT_OLLAMA_CHAT_STARTED, LLMEvent);
wxDEFINE_EVENT(wxEVT_OLLAMA_CHAT_DONE, LLMEvent);
wxDEFINE_EVENT(wxEVT_OLLAMA_CHAT_OUTPUT, LLMEvent);
wxDEFINE_EVENT(wxEVT_OLLAMA_LIST_MODELS, LLMEvent);
wxDEFINE_EVENT(wxEVT_OLLAMA_LOG, LLMEvent);
wxDEFINE_EVENT(wxEVT_OLLAMA_RUN_TOOL, LLMEvent);
