//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: WebToolsBase.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WEBTOOLSBASE_BASE_CLASSES_H
#define WEBTOOLSBASE_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/checkbox.h>
#include <wx/propgrid/manager.h>
#include <wx/propgrid/property.h>
#include <wx/propgrid/advprops.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class WebToolsSettingsBase : public wxDialog
{
protected:
    wxNotebook* m_notebook10;
    wxPanel* m_panel56;
    wxCheckBox* m_checkBoxEnableJsCC;
    wxCheckBox* m_checkBoxEnableXmlCC;
    wxCheckBox* m_checkBoxEnableHtmlCC;
    wxPanel* m_panel12;
    wxPropertyGridManager* m_pgMgr;
    wxPGProperty* m_pgProp26;
    wxPGProperty* m_pgPropLogging;
    wxPGProperty* m_pgProp32;
    wxPGProperty* m_pgPropEcma5;
    wxPGProperty* m_pgPropEcma6;
    wxPGProperty* m_pgPropJQuery;
    wxPGProperty* m_pgPropUnderscore;
    wxPGProperty* m_pgPropBrowser;
    wxPGProperty* m_pgPropChai;
    wxPGProperty* m_pgPropQML;
    wxPGProperty* m_pgProp46;
    wxPGProperty* m_pgPropAngular;
    wxPGProperty* m_pgPropStrings;
    wxPGProperty* m_pgPropNode;
    wxStdDialogButtonSizer* m_stdBtnSizer4;
    wxButton* m_buttonCancel;
    wxButton* m_buttonOK;

protected:
    virtual void OnModified(wxCommandEvent& event) { event.Skip(); }
    virtual void OnJSValueChanged(wxPropertyGridEvent& event) { event.Skip(); }
    virtual void OnOKUI(wxUpdateUIEvent& event) { event.Skip(); }
    virtual void OnOK(wxCommandEvent& event) { event.Skip(); }

public:
    wxCheckBox* GetCheckBoxEnableJsCC() { return m_checkBoxEnableJsCC; }
    wxCheckBox* GetCheckBoxEnableXmlCC() { return m_checkBoxEnableXmlCC; }
    wxCheckBox* GetCheckBoxEnableHtmlCC() { return m_checkBoxEnableHtmlCC; }
    wxPanel* GetPanel56() { return m_panel56; }
    wxPropertyGridManager* GetPgMgr() { return m_pgMgr; }
    wxPanel* GetPanel12() { return m_panel12; }
    wxNotebook* GetNotebook10() { return m_notebook10; }
    WebToolsSettingsBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("WebTools Settings"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~WebToolsSettingsBase();
};

#endif
