name: build-macos-latest

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac. You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_NOSTATS: yes
      CCACHE_MAXFILES: 0
      CCACHE_MAXSIZE: 4G
      CCACHE_LIMIT_MULTIPLE: 0.9
      CCACHE_COMPRESS: yes
      CCACHE_COMPRESSLEVEL: 5
      CCACHE_COMPILERCHECK: "%compiler% -dumpversion"
      CCACHE_COMPILERTYPE: auto
      CCACHE_NODEPEND: yes
      CCACHE_NODIRECT: yes
      CCACHE_CPP2: yes
      CCACHE_SLOPPINESS: "clang_index_store,include_file_ctime,include_file_mtime,locale,time_macros"
      CCACHE_NOHASHDIR: yes
      CCACHE_NOCOMMENTS: yes
      CCACHE_NOINODECACHE: yes
      CCACHE_NOHARDLINK: yes
      CCACHE_NOFILECLONE: yes

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Homebrew update
      run: brew update --preinstall

    - name: Install libraries
      run: |
        checkPkgAndInstall()
        {
          while [ $# -ne 0 ]
          do
            rm -f '/usr/local/bin/2to3'
            if brew ls --versions ${1} ; then
              env HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade ${1}
            else
              env HOMEBREW_NO_AUTO_UPDATE=1 brew install ${1}
            fi
            shift
          done
        }
        checkPkgAndInstall ccache autoconf
        checkPkgAndInstall pkg-config git cmake gtk+3 libssh libedit hunspell

    - name: ccache
      id: ccache
      uses: actions/cache@v1.1.2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-${{ matrix.compiler }}

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: wxWidgets cache
      uses: actions/cache@v1.1.2
      id: wxcache
      with:
        path: ${{ github.workspace }}/wxWidgets.git
        key: wxcache-${{ runner.os }}-${{ matrix.compiler }}-v3.1.4

    - name: wxWidgets download and build
      if: steps.wxcache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ${{ github.workspace }}
        git clone --recursive https://github.com/wxWidgets/wxWidgets.git wxWidgets.git
        cd wxWidgets.git
        git checkout v3.1.4
        mkdir build-release
        cd build-release
        ../configure --enable-shared --enable-monolithic --with-osx_cocoa --disable-debug --disable-mediactrl
        env PATH="/usr/lib/ccache:/usr/libexec/ccache:/usr/local/lib/ccache:/usr/local/libexec/ccache:${PATH}" make -k -j4

    - name: wxWidgets install
      shell: bash
      run: |
        cd ${{ github.workspace }}/wxWidgets.git/build-release
        sudo make install

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${GITHUB_WORKSPACE} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build. You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${BUILD_TYPE} -j4

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${BUILD_TYPE}
