name: macos

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest

    steps:

    - name: Install Codelite's dependencies
      run: |
        # brew update && brew upgrade # fails somehow
        brew install git cmake libssh hunspell bison flex

    # WxWidgets
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: wxWidgets/wxWidgets
          ref: v3.2.5
          submodules: recursive
          path: wxWidgets
    
    - name: Build and install wxWidgets
      run: |
        mkdir wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --enable-shared --enable-monolithic --with-osx_cocoa CXX='clang++ -std=c++17 -stdlib=libc++ -I../src/tiff/libtiff' CC=clang --disable-debug --disable-mediactrl --enable-stl
        make -j$(sysctl -n hw.physicalcpu)
        sudo make install

    # Codelite
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build, test and install Codelite
      run: |
        mkdir build-release
        cd build-release
        brew install autoconf automake libtool gettext
        cmake .. -DCMAKE_BUILD_TYPE=Release -Wno-dev -DBUILD_TESTING=1
        cmake --build . -j $(sysctl -n hw.physicalcpu)
        cmake --build . --target install
        ctest --output-on-failure

# Not the right command/path for codelite
#    - name: codelite --version
#      run: codelite.app/Contents/MacOS/codelite --version || exit 0 # codelite --version returns -1
