name: ubuntu

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
    # wxWidgets
    - name: Install dependencies for wxWidgets
      run: |
        sudo apt-get update
        sudo apt-get install build-essential cmake git libedit-dev libgtk-3-dev libhunspell-dev libsqlite3-dev libssh-dev pkg-config xterm libmariadb-dev libpq-dev

    - name: Checkout WxWidgets
      uses: actions/checkout@v4
      with:
        repository: wxWidgets/wxWidgets
        ref: v3.2.5
        submodules: recursive
        path: wxWidgets

    - name: Build and install wxWidgets
      run: |
        mkdir -p wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --disable-debug_flag --with-gtk=3 --enable-stl
        make -j$(nproc) && sudo make install

    # CodeLite
    - name: Install CodeLite's dependencies
      run: sudo apt-get install build-essential cmake git libpcre2-dev libsqlite3-dev libssh-dev bison flex

    - name: Checkout CodeLite
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build, test and install CodeLite
      run: |
        mkdir build-release
        cd build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_MYSQL=1 -DWITH_POSTGRES=1 -DWITH_CHATAI=1 -DCOPY_WX_LIBS=1 -DBUILD_TESTING=1 -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        make -j$(nproc)
        sudo make install
        ctest --output-on-failure

    - name: codelite --version
      run: xvfb-run -a codelite --version || exit 0 # codelite --version returns -1

    - name: Build CodeLite without SFTP support
      run: |
        mkdir build-release-no-sftp
        cd build-release-no-sftp
        cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_SFTP=0
        make -j$(nproc)
